import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:job_application_tracker/data/database/tables.dart';
import 'package:job_application_tracker/domain/enums/application_status.dart';
import 'package:job_application_tracker/domain/enums/job_enums.dart';

part 'app_database.g.dart';

@DriftDatabase(
  tables: [Applications, StatusHistory, Interviews, ChecklistItems, Notes],
)
class AppDatabase extends _$AppDatabase {
  /// Opens the on-device database file.
  AppDatabase() : super(driftDatabase(name: databaseName));

  /// Uses the given [executor], e.g. `NativeDatabase.memory()` in tests.
  AppDatabase.forTesting(super.executor);

  static const databaseName = 'job_tracker';

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) => m.createAll(),
    // Future schema changes: add `onUpgrade` with step-by-step migrations
    // generated by `dart run drift_dev make-migrations`.
    beforeOpen: (details) async {
      // SQLite ships with foreign keys disabled; cascades rely on them.
      await customStatement('PRAGMA foreign_keys = ON');
    },
  );
}
